spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sparta?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: corud

  jpa:
    hibernate:
      ddl-auto: update  #none,update,validate
    properties:
      hibernate:
        format_sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE


logging.level:
  org.hibernate.SQL: debug
  org.apache.coyote.http11: debug


